### ISSUE TITLE
Strange behavior with event listener

### ISSUE THREAD

**Issue by DouglasHennrich** [appcelerator-modules/titanium-socketio#17]
So, I have two events for this example:
`requestHoist` and `requestHoist:cancel`

```js
socket.on('connect', () => {
     Alloy.Log(`[Socket - Connected]`)

     //
     socket.on('requestHoist', requestHoistFunc)
})

...

//
function requestHoistFunc (evt) {
   // some logic

   socket.on('requestHoist:cancel', resetStatus)
   socket.off('requestHoist', requestHoistFunc) // prevent further requests
}

...

//
function resetStatus () {
  // Here I do an off on all listener and re-add the requestHoist
  socket.off('requestHoist', requestHoistFunc)
  socket.off('requestHoist:cancel', resetStatus)
 
  socket.on('requestHoist', requestHoistFunc)

  // some more logic
}
```

The strange behavior starts now... when I receive that `cancel` event, I **CAN'T** receive `requestHoist` event again unless I put my app on background and comes back to foreground again.
I already tried to set an delay to re-add `requestHoist` listener but still it doesn't work until I do background then foreground and when I do so, when I fire the `requestHoist`(from server) again, I get it twice on the app... I never face that strange behavior before and I don't know why it's happening... maybe someone here could help me?

TiSDK `7.5.1.GA`
Both platforms
iOS -> `1.1.2`
Android -> `2.0.0`

**Comment by janvennemann** [comment]
Hi, i know this issue is pretty old, however, we just released new versions of the socket.io module so i'm going through open issues to close them out.

I'm sure you figured it out by now, but just for the record, there is a logic issue in your posted example. You explicitly call `socket.off('requestHoist', requestHoistFunc)` in your `requestHoistFunc` so you won't receive any of those events. There was also an issue in iOS where sometimes event listerners weren't properly removed, which was fixed in the latest version, which explains the duplicate events you received.
